POST http://localhost:8080/api/invoices
Content-Type: application/json
Accept: application/json

{
  "invoiceNumber": "1454545",
  "issueDate": "2022-06-16",
  "dueDate": "2022-06-18",
  "paymentStatus": "UNPAYED",
  "items": [
    {
      "name": "WC papír",
      "pieces": 5,
      "priceTotal": 1500
    },
    {
      "name": "Toll",
      "pieces": 3,
      "priceTotal": 900
    }
  ],
  "amount": 2400,
  "companyName": "Pannon Egyetem",
  "vatNumber": "12341178-1-45",
  "bankAccountNumber": "42868483-17058745-12345678"
}

###
PUT http://localhost:8080/api/invoices/payment
Content-Type: application/json
Accept: application/json

{
  "invoiceNumber": "123456AB",
  "amount": 1200,
  "bankAccountNumber": "12345876-86496452"
}

###
GET http://localhost:8080/api/invoices/3
Accept: application/json

###
GET http://localhost:8080/api/invoices?vatNumber=2134848-4-58&companyName=Pannon Egyetem
Accept: application/json

###
DELETE http://localhost:8080/api/invoices/2

###
POST http://localhost:8080/api/companies
Content-Type: application/json
Accept: application/json

{
  "companyName": "Infornax Kft",
  "vatNumber": "12345670-1-22",
  "bankAccountNumber": "48964812-86548945-00000000"
}

###
POST http://localhost:8080/api/companies/2
Content-Type: application/json
Accept: application/json

{
  "invoiceNumber": "RS110A16-4545",
  "issueDate": "2022-05-11",
  "dueDate": "2022-05-30",
  "paymentStatus": "UNPAYED",
   "items": [
     {
       "name": "Számológép",
       "pieces": 2,
       "priceTotal": 5000
     },
     {
       "name": "Pénztárca",
       "pieces": 4,
       "priceTotal": 6000
     }
   ],
  "amount": 11000
}

###
GET http://localhost:8080/api/companies/2
Accept: application/json

###
GET http://localhost:8080/api/companies/vat-number/2134848-4-58
Accept: application/json

###
PUT http://localhost:8080/api/companies
Accept: application/json
Content-Type: application/json

{
  "vatNumber": "1234115678-1-45",
  "bankAccountNumber": "12345678-0000000"
}

###
DELETE http://localhost:8080/api/companies/4
Accept: application/json